version: '3'

services:
  api:
    container_name: 'api'
    build: ./api
    command: yarn start
    environment:
      - API_HOST=api
      - API_PORT=4040
    ports:
      - '4040:4040'

  app:
    container_name: 'app'
    build:
      context: ./app
      dockerfile: ./Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://api:4040/
    ports:
      - '3000:3000'
    links:
      - api
